version: "3.8"
services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nawy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_service
    depends_on:
      - database
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://user:password@database:5432/nawy
    ports:
      - "5055:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    depends_on:
      - backend
    ports:
      - "3033:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  db_data:
